# Generated by Django 3.0.5 on 2020-04-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='June', max_length=255),
            preserve_default=False,
        ),
    ]
